### ISSUE TITLE
Weird behavior in vi mode

### ISSUE THREAD

**Issue by GitSquared** [jorgebucaran/autopair.fish#1]
In insert mode, the plugin doesn't react to delimiters at all.
In normal mode, it works, but makes fish go in insert mode while somehow not updating my prompt to reflect that...

![Peek 2020-12-05 11-22](https://user-images.githubusercontent.com/24496417/101239960-3851d180-36ec-11eb-9374-50017cfda305.gif)

In this gif, you can see the Starship prompt which normally points to the left in normal mode and to the right in insert mode.

**What I would expect:**

Plugin doesn't react in normal mode and doesn't switch modes.
Plugin works in insert mode.

**Comment by jorgebucaran** [comment]
@GitSquared Thanks so much for reporting. Just fixed this now. We were using --sets-mode (which sets the mode), instead of --mode, which specifies the bind mode that the bind will be used in (what we want). 💯  

You can update to the latest deployment using:

```console
$ fisher update jorgebucaran/autopair.fish
```

**Comment by GitSquared** [comment]
Thanks, the fix works great! And thanks for making Fisher, too ;)

**Comment by jorgebucaran** [comment]
Thank you for using it!

**Comment by loicnestler** [comment]
I just stumbled upon this because i was encountering the same issue. It seems like this problem only occurs when enabling vi mode by calling the `fish_vi_key_bindings` function, but not when setting the `fish_key_bindings` variable.

Leaving this here in case anyone else has the same issue :)

```fish
# does NOT work with autopair.fish
fish_vi_key_bindings
```

```fish
# DOES work with autopair.fish
set -g fish_key_bindings fish_vi_key_bindings
```
