### ISSUE TITLE
Possible to preserve autocomplete

### ISSUE THREAD

**Issue by albinekb** [jorgebucaran/autopair.fish#10]
Hello! Thanks for this amazing function, it works really well.

One thing i have been missing, is autocompletion for git commit messages, for example:

<img width="414" alt="Screenshot 2023-01-11 at 16 16 52" src="https://user-images.githubusercontent.com/5027156/211843614-aaaeb2a2-41fc-4343-aa6e-3f725f57e25e.png">

Without this library, I could type " and then use some of the autocompleted text to fill my message, but when this library adds the matching " on the end, the autocomplete is gone: 

<img width="234" alt="Screenshot 2023-01-11 at 16 18 00" src="https://user-images.githubusercontent.com/5027156/211843873-b94f5ab9-7cd2-4e47-8434-ea0a8d5a678e.png">

Is it possible to trick fish autocomplete to ignore the ending `"` somehow?

In fish docs, there are things like https://fishshell.com/docs/current/cmds/commandline.html, could this somehow be used to trick fish into not searching with the ending " for autocompletions?

**Comment by injust** [comment]
Is there any workaround to support this functionality?

**Comment by jorgebucaran** [comment]
I've actually run into this myself since the beginning. I usually either just remove the closing " or uninstall autopair, but exploring a clever [`commandline`](https://fishshell.com/docs/current/cmds/commandline.html)-command fix would definitely be worth it—that'd be really useful.
