### ISSUE TITLE
Autopair not loading on new iTerm instances

### ISSUE THREAD

**Issue by crimsonpython24** [jorgebucaran/autopair.fish#12]
I'm not sure what's the issue here, but Autopair does not seem to be loading on iTerm after I quit the terminal...

For instance, when I run `fisher install jorgebucaran/autopair.fish` the autocomplete will work, but not anymore once I quit iTerm and begin a new terminal instance.

Autopair seems to be a rarity that experiences such a problem; I have fzf, nvm, along with a couple other plugins, but most of them loads on startup whereas Autopair does not. Here's my (mostly empty) `~/.config/fish/config.fish`:

```
if status is-interactive
	nvm use 18.16.0
	fzf_configure_bindings --variables=\cv --directory=\cf --git_log=\cg --history=\cr
end
```
Have I missed any steps during the installation? Thanks in advance.

**Comment by jorgebucaran** [comment]
Could you comment out everything in your config.fish and give it another whirl? Just make sure you're running the latest version of Fish, and that there aren't any other plugins creating bindings. And, just for this test, it'd be best if you're not using Starship or Oh My Fish!. Lastly, uninstall, and reinstall autopair in a fresh terminal window. 

Let's see if this does the trick!

**Comment by crimsonpython24** [comment]
Thanks for the reply!

Commented out my `config.fish` in `~/.config/fish/config.fish` (macOS):
```
if status is-interactive
	#nvm use 18.16.0
	#fzf_configure_bindings --variables=\cv --directory=\cf --git_log=\cg --history=\cr
end
```
Fish is version `3.6.1` and I'm not using Starship or OMF. 
 
Unfortunately, even though `fisher install jorgebucaran/autopair.fish` in the fresh terminal window works, it does not anymore once I start a new terminal (I have reinstalled autopair in a new terminal window after commenting out my config.fish). Fzf does have keybindings, though.

What could be other possible causes?

**Comment by jorgebucaran** [comment]
[conf.d/autopair.fish](https://github.com/jorgebucaran/autopair.fish/blob/main/conf.d/autopair.fish) should run with every new terminal. Can you confirm that's happening? Also, you can use `bind` to list bindings. Try running `bind` in the terminal where you just installed autopair, and then do the same in a new tab where the plugin isn't working, just to see if there's any difference in the bindings listed. You can also take a peek at the specific bindings we set up [right here](https://github.com/jorgebucaran/autopair.fish/blob/4d1752ff5b39819ab58d7337c69220342e9de0e2/conf.d/autopair.fish#L16-L18).

**Comment by crimsonpython24** [comment]
>[conf.d/autopair.fish](https://github.com/jorgebucaran/autopair.fish/blob/main/conf.d/autopair.fish) should run with every new terminal. Can you confirm that's happening?

How can I check so? 

Update, it does seem like something is missing:
```bash
bind \x7f _autopair_backspace
bind -k backspace _autopair_backspace
bind \t _autopair_tab
bind '(' _autopair_insert_left\ \\\(\ \\\)
bind ')' _autopair_insert_right\ \\\)
bind '[' _autopair_insert_left\ \\\[\ \\\]
bind ']' _autopair_insert_right\ \\\]
bind '{' _autopair_insert_left\ \\\{\ \\\}
bind '}' _autopair_insert_right\ \\\}
bind '"' _autopair_insert_same\ \\\"
bind \' _autopair_insert_same\ \\\'
```
These lines are missing in the second terminal window where Autopair wouldn't run, after Autopair has been installed in the first. How can I add these lines to all new terminal sessions, if doing so is the solution to my issue?

**Comment by jorgebucaran** [comment]
Just tweak [conf.d/autopair.fish](https://github.com/jorgebucaran/autopair.fish/blob/main/conf.d/autopair.fish).

Try removing `status is-interactive || exit` to make sure it runs no matter what, or `echo` something to the console (or use `tput bel` to play a sound).

**Comment by crimsonpython24** [comment]
I replaced `status is-interactive || exit` with `echo "running"`

When I relaunch the terminal, "running" will be displayed, but the autopair function itself still isn't running (e.g. when I type `"`, the pair does not show up). I ran `bind` one more time, and the lines above 
> ```shell
> bind \x7f _autopair_backspace
> bind -k backspace _autopair_backspace
> bind \t _autopair_tab
> bind '(' _autopair_insert_left\ \\\(\ \\\)
> bind ')' _autopair_insert_right\ \\\)
> bind '[' _autopair_insert_left\ \\\[\ \\\]
> bind ']' _autopair_insert_right\ \\\]
> bind '{' _autopair_insert_left\ \\\{\ \\\}
> bind '}' _autopair_insert_right\ \\\}
> bind '"' _autopair_insert_same\ \\\"
> bind \' _autopair_insert_same\ \\\'
> ```
still does not show up.

**Comment by crimsonpython24** [comment]
Also, interactive mode does not seem to be the issue. This is my current `conf.d/autopair.fish`:
```bash
status is-interactive || exit
echo "running"

set --global autopair_left "(" "[" "{" '"' "'"
#...
```
And my fish initialization still reads
```bash
Last login: Fri Jun 16 16:19:23 on ttys000
running
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
user@mbp ~>
```

**Comment by crimsonpython24** [comment]
As another update, I don't think iTerm is to blame. I ran the modified script in MacOS' default terminal, and the script still doesn't work -- despite how "running" still shows up.

**Comment by crimsonpython24** [comment]
I found a workaround. If I manually add the keybindings into my config.fish, as shown:
```bash
if status is-interactive
	nvm use 18.16.0
	fzf_configure_bindings --variables=\cv --directory=\cf --git_log=\cg --history=\cr
	bind \x7f _autopair_backspace
	bind -k backspace _autopair_backspace
	bind \t _autopair_tab
	bind '(' _autopair_insert_left\ \\\(\ \\\)
	bind ')' _autopair_insert_right\ \\\)
	bind '[' _autopair_insert_left\ \\\[\ \\\]
	bind ']' _autopair_insert_right\ \\\]
	bind '{' _autopair_insert_left\ \\\{\ \\\}
	bind '}' _autopair_insert_right\ \\\}
	bind '"' _autopair_insert_same\ \\\"
	bind \' _autopair_insert_same\ \\\'
end
```
then Autopair's keybindings will be effective (in previous cases, it has already loaded, but the keybindings won't show up). 

Meanwhile, I have uninstalled and reinstalled Autopair through fisher each time before I modify something new, so I am sure that my modifications are based on the latest version.

**Comment by jorgebucaran** [comment]
Are you using vi mode?

**Comment by crimsonpython24** [comment]
Can I ask what do you mean?

**Comment by crimsonpython24** [comment]
Sorry, I think I've misunderstood what you've said. I am using the default key bindings.

```bash
user@mbp ~> echo $fish_key_bindings
fish_default_key_bindings
```

**Comment by crimsonpython24** [comment]
The weird thing is, everything seems to be loaded, but that they keybindings wouldn't work... for example, I have added even more `echo` statements below:

```bash
status is-interactive || exit
echo "Test1"

# ...

function _autopair_fish_key_bindings --on-variable fish_key_bindings
    echo "Test2"
    set --query fish_key_bindings[1] || return

    # ...

    printf "%s\n" $autopair_pairs | while read --local left right --delimiter ""
        bind --mode $mode[-1] --erase $left $right
        echo "Test3"
```

And my fish loading output becomes
```bash
Last login: Fri Jun 16 17:20:41 on ttys001
Test1
Test2
Test3
Test3
Test3
Test3
Test3
Now using Node v18.16.0 (npm 9.5.1) ~/.local/share/nvm/v18.16.0/bin/node
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
user@mbp ~>
```

**Comment by jorgebucaran** [comment]
FWIW it works for me at least. I'm also on Fish 3.6.1.

**Comment by crimsonpython24** [comment]
Could I have installed fisher incorrectly so that the plugins do not load, or is that irrelevant?

**Comment by crimsonpython24** [comment]
Since manually pasting the keybindings into `~/.config/fish/config.fish` does work and that it seems I'm the only one with issue, I think I'll close it for now. Maybe I'll find out the reason once I start encountering issues from other packages.
