### ISSUE TITLE
Why fishpkg/fish-menu redirect to this repo?

### ISSUE THREAD

**Issue by tuxfamily** [jorgebucaran/autopair.fish#5]
Hello.

I just upgraded "fisher" (from 2.x to 3.x) and I don't understand why `fisher install fishpkg/fish-menu` now install this repo that does not seems related in any way.

```bash
# fisher install fishpkg/fish-menu
fisher install version 4.3.0
Fetching https://codeload.github.com/fishpkg/fish-menu/tar.gz/HEAD
Installing fishpkg/fish-menu
           /Users/xxx/.config/fish/functions/_autopair_backspace.fish
           /Users/xxx/.config/fish/functions/_autopair_insert_left.fish
           /Users/xxx/.config/fish/functions/_autopair_insert_right.fish
           /Users/xxx/.config/fish/functions/_autopair_insert_same.fish
           /Users/xxx/.config/fish/functions/_autopair_tab.fish
           /Users/xxx/.config/fish/conf.d/autopair.fish
Updated 1 plugin/s
```

Could you explain why 'fish-menu' has disappeared and if there an alternative?

Thank you.

**Comment by jorgebucaran** [comment]
No, I'm afraid there isn't. It seems you were the only one using it. I can't remember what plugins depended on it. 2015 is a long time ago, even for mayor software, and all my plugins are up to date now.

**Comment by jorgebucaran** [comment]
The latest version of Fisher is 4.3 by the way. See the README for upgrade instructions.
