### ISSUE TITLE
Renaming conf.d file

### ISSUE THREAD

**Issue by tosti007** [jorgebucaran/autopair.fish#6]
Hey there! 

I just found out about this plugin and am definitely going to be using it! However I noticed that the file in the `conf.d` file is not prepended with an underscode (i.e. `_`). For the `functions` folder the files are prepended with an underscore.

Being a person that stole someone else's dotfiles my gitignore already ignores all fish files starting with an underscore, but since the file does not have one it is not auto-ignored. 

Hence my main question: Could this file be renamed to adhere to the underscore usage? Or is there a different reason that I am missing here?

**Comment by jorgebucaran** [comment]
The files in the functions directory start with an underscore because the functions it contains are for internal use of this plugin. The file in conf.d is this plug-in's entry point.

**Comment by jorgebucaran** [comment]
The files in the functions directory start with an underscore because they are "internal"-use. The file in conf.d is this plug-in's entry point.
